#!/bin/bash

if [ -d /root ]
then
echo ""
else
mkdir /root
fi
cd /root/
if [[ -e /bin/instalacao1 ]]; then
instalar
exit
sleep 4s
else
 if [[ -e /bin/instalacao2 ]]; then
instalar
exit
sleep 4s
else
  if [[ -e /bin/instalacao3 ]]; then
instalar
exit
sleep 4s
else
   if [[ -e /bin/instalacao4 ]]; then
instalar
exit
sleep 4s
else
echo " "
clear
   fi
  fi
 fi
fi
clear
sleep 1s
echo -e "\033[1;31mESTE ES UN SCRIPT MODIFICADO Y EDITADO POR @DarksideBlak!\033[0m"
echo -e "\033[1;36mESTE ES UN GERENCIADOR PARA SU VPS CON UNA SERIE DE HERRAMIENTAS UTILES!\033[1;31m"
read -p"ENTER PARA SEGUIR "
echo -e "\033[1;36mESTE SCRIPT FUE CREADO PARA SO 
-----------------
DEBIAN
UBUNTU
-----------------
PUEDE HABER INCOMPATIBILIDAD SI LO USA EN OTROS SO!!!\033[1;31m"
read -p"ENTER PARA SEGUIR "
echo -e "\033[0m"
sleep 1s
echo -e "\033[1;31mSE ESTA PREPARANDO SU SISTEMA INICIARA EN 3 SEGUNDOS...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36mCOMENZANDO...\033[0m"
sleep 1s
echo -e "\033[1;36mPREPARANDO DOWLOAD...\033[0m"
apt-get upgrade -y 1>/dev/null 2>/dev/null
echo  -e "\033[1;32m"
apt-get install zip -y
sleep 1s
echo  -e "\033[0m"
echo -e "\033[1;36mREALIZANDO DOWLOAD...\033[0m"
cd /root/
sleep 1s
wget -O manager https://www.dropbox.com/s/dq64b1il53iy6zs/admmanager.zip?dl=0 -o /dev/null
sleep 4s
echo -e "\033[1;36mPREPARANDO ARCHIVOS...\033[0m"
sleep 4s
echo -e "\033[1;36mEXTRAYENDO ARCHIVOS...\033[0m"
echo  -e "\033[1;32m"
unzip /root/manager
echo  -e "\033[0m"
sleep 4s
echo -e "\033[1;36mARCHIVOS EXTRAIDOS!...\033[0m"
sleep 4s
echo -e "\033[1;36mDANDO PERMISO A LOS ARCHIVOS...\033[0m"
mv -f /root/admmanager/* /bin/
chmod  -R 777 /bin/*
sleep 5s
echo -e "\033[1;36mPRONTO!!!...\033[0m"
sleep 4s
echo -e "\033[1;36mEXECUTANDO INSTALADOR\033[0m"
sleep 4s
echo -e "\033[1;36mESPERE...\033[0m"
rm -rf /root/manager*
sleep 1s
rm -rf /root/admmanager*
sleep 1s
rm -rf /root/inst*
sleep 1s
echo -e "\033[1;36mESPERE...\033[0m"
sleep 2s
echo -e "\033[1;31mLA INSTACION INICIA EN  3 SEGUNDOS...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36m...\033[0m"
sleep 1s
echo -e "\033[1;36mINICIANDO...\033[0m"
instalar
sleep 2s
clear
exit
